/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MarketSummary {
  'name' : string,
  'currentValue' : number,
  'change' : number,
}
export interface ScanCriteria {
  'volumeThreshold' : [] | [bigint],
  'minRSI' : [] | [number],
  'maxPrice' : [] | [number],
  'maxPercentChange' : [] | [number],
  'minPercentChange' : [] | [number],
  'maxRSI' : [] | [number],
  'minPrice' : [] | [number],
  'aboveTwoHundredMA' : [] | [boolean],
  'aboveFiftyMA' : [] | [boolean],
  'macdSignalFilter' : [] | [string],
}
export interface Stock {
  'rsi' : number,
  'macdSignal' : string,
  'volume' : bigint,
  'sector' : string,
  'fiftyDayMA' : number,
  'companyName' : string,
  'percentChange' : number,
  'price' : number,
  'twoHundredDayMA' : number,
  'symbol' : string,
}
export interface _SERVICE {
  'addToWatchlist' : ActorMethod<[string], undefined>,
  'getAllStocks' : ActorMethod<[], Array<Stock>>,
  'getMarketSummary' : ActorMethod<[], Array<MarketSummary>>,
  'getStock' : ActorMethod<[string], Stock>,
  'getWatchlist' : ActorMethod<[], Array<string>>,
  'removeFromWatchlist' : ActorMethod<[string], undefined>,
  'scanStocks' : ActorMethod<[ScanCriteria], Array<Stock>>,
  'scanStocksPaginated' : ActorMethod<
    [ScanCriteria, bigint, bigint],
    Array<Stock>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];