/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Stock = IDL.Record({
  'rsi' : IDL.Float64,
  'macdSignal' : IDL.Text,
  'volume' : IDL.Nat,
  'sector' : IDL.Text,
  'fiftyDayMA' : IDL.Float64,
  'companyName' : IDL.Text,
  'percentChange' : IDL.Float64,
  'price' : IDL.Float64,
  'twoHundredDayMA' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const MarketSummary = IDL.Record({
  'name' : IDL.Text,
  'currentValue' : IDL.Float64,
  'change' : IDL.Float64,
});
export const ScanCriteria = IDL.Record({
  'volumeThreshold' : IDL.Opt(IDL.Nat),
  'minRSI' : IDL.Opt(IDL.Float64),
  'maxPrice' : IDL.Opt(IDL.Float64),
  'maxPercentChange' : IDL.Opt(IDL.Float64),
  'minPercentChange' : IDL.Opt(IDL.Float64),
  'maxRSI' : IDL.Opt(IDL.Float64),
  'minPrice' : IDL.Opt(IDL.Float64),
  'aboveTwoHundredMA' : IDL.Opt(IDL.Bool),
  'aboveFiftyMA' : IDL.Opt(IDL.Bool),
  'macdSignalFilter' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addToWatchlist' : IDL.Func([IDL.Text], [], []),
  'getAllStocks' : IDL.Func([], [IDL.Vec(Stock)], ['query']),
  'getMarketSummary' : IDL.Func([], [IDL.Vec(MarketSummary)], ['query']),
  'getStock' : IDL.Func([IDL.Text], [Stock], ['query']),
  'getWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
  'scanStocks' : IDL.Func([ScanCriteria], [IDL.Vec(Stock)], ['query']),
  'scanStocksPaginated' : IDL.Func(
      [ScanCriteria, IDL.Nat, IDL.Nat],
      [IDL.Vec(Stock)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Stock = IDL.Record({
    'rsi' : IDL.Float64,
    'macdSignal' : IDL.Text,
    'volume' : IDL.Nat,
    'sector' : IDL.Text,
    'fiftyDayMA' : IDL.Float64,
    'companyName' : IDL.Text,
    'percentChange' : IDL.Float64,
    'price' : IDL.Float64,
    'twoHundredDayMA' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const MarketSummary = IDL.Record({
    'name' : IDL.Text,
    'currentValue' : IDL.Float64,
    'change' : IDL.Float64,
  });
  const ScanCriteria = IDL.Record({
    'volumeThreshold' : IDL.Opt(IDL.Nat),
    'minRSI' : IDL.Opt(IDL.Float64),
    'maxPrice' : IDL.Opt(IDL.Float64),
    'maxPercentChange' : IDL.Opt(IDL.Float64),
    'minPercentChange' : IDL.Opt(IDL.Float64),
    'maxRSI' : IDL.Opt(IDL.Float64),
    'minPrice' : IDL.Opt(IDL.Float64),
    'aboveTwoHundredMA' : IDL.Opt(IDL.Bool),
    'aboveFiftyMA' : IDL.Opt(IDL.Bool),
    'macdSignalFilter' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addToWatchlist' : IDL.Func([IDL.Text], [], []),
    'getAllStocks' : IDL.Func([], [IDL.Vec(Stock)], ['query']),
    'getMarketSummary' : IDL.Func([], [IDL.Vec(MarketSummary)], ['query']),
    'getStock' : IDL.Func([IDL.Text], [Stock], ['query']),
    'getWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
    'scanStocks' : IDL.Func([ScanCriteria], [IDL.Vec(Stock)], ['query']),
    'scanStocksPaginated' : IDL.Func(
        [ScanCriteria, IDL.Nat, IDL.Nat],
        [IDL.Vec(Stock)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };